### ISSUE TITLE
triflake example not working - whitebox is interpreted as color

### ISSUE THREAD

**Issue by kronpano** [after12am/eisenscript#109]
The [tribox example](https://after12am.github.io/eisenscript-docs/build/docs/example-tri-flake) does not work 
The rule
{rz 60 x 1/3 s 0.20 1 0.2 } whitebox

gives an error that "s 0.20 1 0.2 } xxx" a primitive or rule name is expected but a color was found.

**Comment by after12am** [comment]
Thank you! Fix it
