### ISSUE TITLE
web app implementation

### ISSUE THREAD

**Issue by after12am** [after12am/eisenscript#35]
- mv renderer tools to app/

**reference**
http://gamingjs.com/ice/
http://ui-patterns.com/patterns/CompletenessMeter/examples/17153
http://ui-patterns.com/users/1/collections/account-deletion/screenshots/17012
http://ui-patterns.com/patterns/CopyBox/examples/17039

**Comment by kronpano** [comment]
gamingjs.com/ice looks quite promising!! Would be a very nice UI I think.

**Comment by after12am** [comment]
Thank you for comment. I'll try it below forked repository.
https://github.com/after12am/eisenscript-editor

But it may take time. And I'll update the documents of usage little by little on my weekend.
I'm Sorry,

**Comment by after12am** [comment]
Though using old version of threejs, I made eisenscript work on the browser.
https://after12am.github.io/eisenscript-editor/

Mouse operation is not supported yet.

**Comment by after12am** [comment]
version up to v1.1.16
https://after12am.github.io/eisenscript-editor/
