### ISSUE TITLE
colorpool implementation

### ISSUE THREAD

**Issue by after12am** [after12am/eisenscript#4]
- colorpool implementation
- prepare example

```
set colorpool [scheme]
```

http://structuresynth.sourceforge.net/reference.php

**Comment by kronpano** [comment]
implementation would be cool

set colorpool list:#f00,#0f0,#00f,#ff0
or
set colorpool list:red,blue,green,yellow

**Comment by after12am** [comment]
@kronpano v1.3.1 supports https://github.com/after12am/eisenscript/issues/4#issuecomment-611951901

**Comment by kronpano** [comment]
Very cool. 
Thanks

**Comment by after12am** [comment]
```
set colorpool list:orange,white,white,white,grey

10 * { x 1 color random } box
```

![image](https://user-images.githubusercontent.com/678921/89701420-d1a4ed00-d971-11ea-8f76-30b68b6a4ff0.png)

![Default_es__-_Structure_Synth](https://user-images.githubusercontent.com/678921/89701425-dec1dc00-d971-11ea-8be7-19ab565b71e1.png)

**Comment by after12am** [comment]
randomhue

![image](https://user-images.githubusercontent.com/678921/89701443-10d33e00-d972-11ea-9467-3cd20b83f765.png)

![Default_es__-_Structure_Synth](https://user-images.githubusercontent.com/678921/89701449-192b7900-d972-11ea-98f2-6ca4479e5da0.png)

**Comment by after12am** [comment]
randomrgb

```
set colorpool randomrgb

10 * { x 1 color random } box
```

![image](https://user-images.githubusercontent.com/678921/89701481-56900680-d972-11ea-9c87-68972c85df3b.png)

![Default_es__-_Structure_Synth](https://user-images.githubusercontent.com/678921/89701488-64458c00-d972-11ea-96ca-afefb42a31ed.png)
