### ISSUE TITLE
Possible to implement squashed spheres and other THREE primitives?

### ISSUE THREAD

**Issue by kronpano** [after12am/eisenscript#43]
I am using the original version of Structure Synth quite a bit and would be very interested in trying to bring it to web browsers and possibly extend it - torus, cylinders and other THREE primitives and possibly squashed spheres.
Also there are quite a few lighting options in THREE.js 

My problem is, I have worked with javascript but I am not sure about the process to get it all to work together. Is there a bit more of a description of the workflow and the tools needed?

Sorry if this is a bit of a newbie question but I haven't used some of the tools needed.

**Comment by kronpano** [comment]
OK, I got it to work - looking forward to playing with it - and hopefully extending it.

**Comment by kronpano** [comment]
Well, I guess it would all be a lot easier if I knew what I was doing.
Managed to get it to work with the new version of three.js and a three tutorial file - so I can spin it around and zoom in. The eisen script is just showing a couple of different primitives

> all
rule all{
  10 * {s 1.2 1 1 rx 5 z 4} 1 * {s 4} sphere
  10 * {s 1.2 rx 5 z -1.5} 1 * {s 2}  torus
  10 * {s 1.2 y 1.3} pyra3  // 3 sided pyramid from cone
  10 * {s 0.8 1 1.1 y -2.5} 1 * {s 4} sphere
  10 * {s 1.2 rz 5 x 1.6} pyra4 // 4 sided pyramid from cone
  10 * {s 1.2 rz 5 y 0.18 x -1.8} cone // well, a cone
}

So definitely more playing needed!!! It looks promising - I also read somewhere about CSG using three.js - this is the one thing I have been missing a long time since leaving POV ray and I think it would work well with Structure Synth to create basic shapes.
![image](https://cloud.githubusercontent.com/assets/22873114/19493672/97ef60fe-9573-11e6-95a4-10eb1beea7dd.png)

**Comment by after12am** [comment]
great works!

> possibly extend it - torus, cylinders and other THREE primitives and possibly squashed spheres.

Yes, I can support these primitives. But I want to write test codes for avoiding degration befor supporting these.

**Comment by after12am** [comment]
> I am not sure about the process to get it all to work together. Is there a bit more of a description of the workflow and the tools needed?

I am sorry for my poor documentation. It needs to reorganize and expand the documentation.

**Comment by after12am** [comment]
added cylinder, triangle, line primitives. #58

**Comment by after12am** [comment]
I can support squashed spheres, but I think it is not basic primitive. So if uses squash, you would do as following.

```
rule squash {
  { s 1 .2 1 } box
}
squash
```

**Comment by after12am** [comment]
What shape is good with squash? Is this ok?

https://after12am.github.io/eisenscript-editor/#B/q1ZIVNCztFSoVSguLE0szgAA

**Comment by after12am** [comment]
If the issue hasn't been fixed, please reopen issue.
