### ISSUE TITLE
Some sort of rounding errors????

### ISSUE THREAD

**Issue by kronpano** [after12am/eisenscript#46]
Another regular structure 
18 \* {ry 12 y -0.9 s 1.3 1 1}box
leads to this:
![image](https://cloud.githubusercontent.com/assets/22873114/19538168/c0734220-964a-11e6-8bca-a08be5c2bdd7.png)
there is this strange step after 14 steps.

Do the same with a smaller angle and it looks OK
18 \* {ry 10 y -0.9 s 1.3 1 1}box
![image](https://cloud.githubusercontent.com/assets/22873114/19538244/13660846-964b-11e6-8501-0578768f51c5.png)

When the angle gets over 180 there is this jump???
Not really sure.

**Comment by after12am** [comment]
well, I got terrible result when I used babylonjs.

![localhost_9000_tests_babylonjs_html_](https://cloud.githubusercontent.com/assets/678921/19620339/6d3f67d2-98b6-11e6-9248-f379dd7872e2.png)
![localhost_9000_tests_babylonjs_html_ 2](https://cloud.githubusercontent.com/assets/678921/19620341/6e865114-98b6-11e6-9059-0dff268f9d29.png)

**Comment by after12am** [comment]
It might be lighting of renderer causes this problem.

**Comment by kronpano** [comment]
I will have a look at the object data generated. If that is OK the problem lies somewhere else - true.
I guess with all the data available it would even be possible to generate python scripts for Blender and other "exporters". 
Great work!!!! 
Will surely check out the progress you made next week.
Thanks for all the hard work!!!!

**Comment by kronpano** [comment]
Did a bit more investigation on this one and I am not sure it is only the renderer.
Here is a screen shot like the one I posted first:
![image](https://cloud.githubusercontent.com/assets/22873114/19653351/1f61db74-9a0c-11e6-9c7b-f60657d43786.png)

I "extended" the code a bit to export translate, scale and rotation from the object matrix to a csv file.
This can be opened in Sverchok, a Blender add-on and then you can see the data modelled in Blender.
Here is the screenshot of that:
![screensverchokstack](https://cloud.githubusercontent.com/assets/22873114/19653428/6b5a6154-9a0c-11e6-9362-f897088b39a1.png)

The camera perspective is slightly different but you can see that the data really has that jump on the fourth plate from the bottom - not sure though why and where it comes from.

**Comment by kronpano** [comment]
You might be right that this is a limitation of three.js
In this issue on three.js https://github.com/mrdoob/three.js/issues/3845 they are talking about:

> This means that when the matrix is applied to a vector, the rotation is applied first, and the scale is applied second.
When the scale is non-uniform, a transform of this form cannot, in general, be decomposed into a scale followed by a pure rotation.
What this means is that parents with non-uniform scale need to be avoided. It is OK if (childless) children have non-uniform scale. 

I am not 100% that this is the problem but - after playing around a bit more - it looks like it could be.

**Comment by after12am** [comment]
This looks fixed now. @kronpano Check it out please.

> 18 * {ry 12 y -0.9 s 1.3 1 1}box

![screencapture-192-168-11-5-9000-examples-1586744942556](https://user-images.githubusercontent.com/678921/79087372-031dfb00-7d7a-11ea-8b7d-198e25522364.png)

![image](https://user-images.githubusercontent.com/678921/79087378-087b4580-7d7a-11ea-9c4f-8a3e18768ed0.png)

**Comment by after12am** [comment]
If the issue hasn't been fixed, please reopen issue.
