### ISSUE TITLE
Starter tutorial for Noob

### ISSUE THREAD

**Issue by enzyme69** [after12am/eisenscript#51]
In order to use this Eisenscript JS, where is the best way to do it? Is the example included in the ZIP? 

I always have issue with JS in regards to "Server" :(

**Comment by after12am** [comment]
This zip file is the best for now. And the example are under `app/tests/` directory.
https://github.com/after12am/eisenscript/releases/tag/v1.1.9

I had not thought about who want to uses this library directly.
I had ever assumed to use through web app like [this](https://after12am.github.io/eisenscript-editor/). So I was so surprised that there are the people who want to use it directly.

I have to expand the documentation.
Please give me a time. I am trying to make source code testable.

And then, I refactor the source code and update the documentation.

**Comment by after12am** [comment]
> I always have issue with JS in regards to "Server" :(

"Server" is not required in this app.

**Comment by after12am** [comment]
Some command line operation is:

(1) download the source code.
https://github.com/after12am/eisenscript/releases/tag/v1.1.9

(2) unzip and change directory to eisenscript-1.1.9 in your terminal.

(3) install npm packages

```
% npm install
```

(4) start server

```
% gulp serve
```

(5) open `http://localhost:9000/tests/index.html` in your browser.

**Comment by enzyme69** [comment]
Ok I will give it a try. Thanks!

**Comment by after12am** [comment]
You are welcome!
