### ISSUE TITLE
Scaling affects rotation ?

### ISSUE THREAD

**Issue by kronpano** [after12am/eisenscript#53]
Using the following script:

> tower
> rule tower md 44 {
>     {s 2 5 3 }box
>     {y 5 rx 10 rz 10 s 0.95 } tower
> }
> Produces the following image:
> ![browsereven](https://cloud.githubusercontent.com/assets/22873114/19629663/96446f04-9971-11e6-9836-723b3013d332.jpg)

Now the only change is to change the scaling in the recursive function call:

> tower
> rule tower md 44 {
>     {s 2 5 3 }box
>     {y 5 rx 10 rz 10 s 0.95 1 1 } tower
> }
> which then produces the following image:
> ![browseruneven](https://cloud.githubusercontent.com/assets/22873114/19629677/00db114c-9972-11e6-90a1-0623d093a7d1.jpg)

There are quite a few wobbles when it comes to the rotation and there seem to be points where the box is actually growing - not shrinking - even though the rule is same or smaller.

It leads to an irregular image when all it should do is shrink in the direction of one axis.

This behaviour will be different from the original Structure Synth because there the shearing happened when rotation and scaling was used in the same rule .

**Comment by kronpano** [comment]
OK, it really is the case - scaling affects the rotation BUT only the non-uniform scaling.
So rule containing "{ry 10 s 1.5}box" that is OK but if you have rotation and non uniform scaling like
"{ ry 10 s 1.5 1 1} box" that actually affects the rotation.

As example I use the simple script of

> 9 * {ry 22.5 y -1 s 1.4} 1 * {ry -22.5}box

This gives you a nice tower of stacked boxes.
In the image you can also see the angle value - I put a debug statement into the code when the element is actually added to the scene which shows the x, y and z angles:

>    var rot2 = new THREE.Euler().setFromRotationMatrix (object.matrix,"YZX")
	console.log(rot2._x * 180 / Math.PI,rot2._y * 180 / Math.PI,rot2._z * 180 / Math.PI )
	switch (object.type) {
      case 'background': clearColor(object.color); break;
      case 'primitive': lesson10.MyAddPrimitive(object); break;
    }
These angles are extracted from the Matrix4 - the quaternions - which I still don't fully understand.

OK - first uniform scaling:
script:  9 * {ry 22.5 y -1 s 1.4} 1 * {ry -22.5}box (angle chosen to make it easy to see
![image](https://cloud.githubusercontent.com/assets/22873114/19683198/39c21e32-9aa9-11e6-8991-78fd4020bdf6.png)
 in the degub you can see angles are close enough to 0,45,90,135 and 180
and now non uniform scaling:

script: 9 * {ry 22.5 y -1 s 1.4 1 1 } 1 * {ry -22.5}box
![image](https://cloud.githubusercontent.com/assets/22873114/19683293/8ff70466-9aa9-11e6-8eac-b61474c91d36.png)

it also gets worse if one scaling goes up and one down:
script: 9 * {ry 22.5 y -1 s 1.4 1 0.8 } 1 * {ry -22.5}box
![image](https://cloud.githubusercontent.com/assets/22873114/19683405/f8fdbab8-9aa9-11e6-8578-ed1ef119bc3a.png)
After nine rotations of 22.5 it barely reaches 90 degrees not the 180 you would expect.

Looking at the code it is all connected to the Matrix4 (and matrix,js) in interpreter.js where the values are stored and  renderer.js addPrimitive where the object matrix is applied.

I am not sure matrix.js is really needed - looks to me as if the later versions of three have all the functions to deal with Matrix4 - the angles need to be give in radians but that is a simple conversion.

Haven't tried to rewrite it to use the three.js build in functions to deal with Matrix4

**Comment by kronpano** [comment]
Looking at three.js it might be connected to https://github.com/mrdoob/three.js/issues/3185 ???
But - as said before - I don;t fully understand the Matrix4.

**Comment by after12am** [comment]
Sorry. I came home now. I have to work much more hard for schedule delay in this week. Maybe.. next few weeks.

**Comment by kronpano** [comment]
No worries - we all know that sadly work - real paid work is more important.
Will probably play a bit more and possibly raise issues but that does NOT mean I expect anything.

Everybody does things in their time - thanks for such a great start !!!

**Comment by after12am** [comment]
It looks fixed now.

> tower
> rule tower md 44 {
> {s 2 5 3 }box
> {y 5 rx 10 rz 10 s 0.95 } tower
> }

![screencapture-192-168-11-5-9000-examples-1586744670715](https://user-images.githubusercontent.com/678921/79087152-64919a00-7d79-11ea-8fb6-e64774330776.png)

> tower
> rule tower md 44 {
> {s 2 5 3 }box
> {y 5 rx 10 rz 10 s 0.95 1 1 } tower
> }

![screencapture-192-168-11-5-9000-examples-1586744446686](https://user-images.githubusercontent.com/678921/79086958-d9180900-7d78-11ea-9c46-bef9268357e7.png)

> 9 * {ry 22.5 y -1 s 1.4} 1 * {ry -22.5}box

![screencapture-192-168-11-5-9000-examples-1586744818935](https://user-images.githubusercontent.com/678921/79087289-bcc89c00-7d79-11ea-964c-7369ac093287.png)

![screencapture-192-168-11-5-9000-examples-1586744831516](https://user-images.githubusercontent.com/678921/79087292-be925f80-7d79-11ea-89f3-a08728154b9d.png)

**Comment by after12am** [comment]
@kronpano Is it ok to close this issue?

**Comment by after12am** [comment]
If the issue hasn't been fixed, please reopen issue.
