### ISSUE TITLE
mirroring not implemented

### ISSUE THREAD

**Issue by kronpano** [after12am/eisenscript#73]
Mirroring in Structure synth is fx, fy, fz which mirrors respectively on the x,y and z axis
This allows something like 
2 *{fx} 
which gives you the object AND the x-axis mirrored object.

At the moment this can be achieved using the matrix but 2 things:
{m -1 0 0 0 1 0 0 0 1} 
is quite a bit to write as opposed to fx
AND
the matrix operator doesn't  support multiples 2 *{m .. correctly

Example
2 * {m -1 0 0 0 1 0 0 0 1 h 120}{x 3 s 2}box 
creates a blue box at x -3 - it is blue because it applied the m and h operator twice to the original red box - it should (to be a real L-system) apply the m operator to the original red box once - creating a green one at x -3 and then apply the m operator on that and create a blue one at x 3

1 * {m -1 0 0 0 1 0 0 0 1 h 120}{x 3 s 2}box
creates a green box at x -3 because m and h have been applied only once

So having fx, fy, fz would be really cool and if they - and the m operator - worked with multiples that would be even better.

**Comment by after12am** [comment]
Ok, thank you. But this looks like a bit difficult.

**Comment by kronpano** [comment]
Hi there,

saw that there are another batch of fixes and changes - looking good!!!

Any chance of getting the mirror operator in (fx, fy, fz)  or matrix  operator fixed ?
If you can use 2 * {m -1 0 0 0 1 0 0 0 1} then that can be used for mirroring but at the moment this command results in one cube with the normal inside out ( or that's what it looks like).

Cheers

**Comment by after12am** [comment]
@kronpano I'm not sure how to implement it, but I tried it. How is this? Is it as you expected?

https://after12am.github.io/eisenscript-editor/#B/q1ZIq1CoUDBUqFVIyq8AAA==

**Comment by kronpano** [comment]
Hmm, not really
the biggest problem is not that the normals inverted but that it doens't work with multiples
`2 * {fx} 1 * {x 5 } box` should (according to the original StructureSynth) produce two boxes one a x=5 and one mirrored (and possibly normals inverted) at x= -5
`2 * { fy} 2 * {fx } 1 * {x 1  y 3} box` should produce 4 boxes

You code seems to only ever produce one visible box - even though the developer tools say 'Build done. Created 4 objects.' but I can't see them???
Then again - it could just be me.
Same happens with the matrix operation but I think there might just be a problem with objects being created BUT not being visible because of inverted normals (e.g. one-sided materials - just a guess)??

**Comment by kronpano** [comment]
Somehow it seem to work - but why can't I see more than one cube ??
Just tried that one [skyship](https://after12am.github.io/eisenscript-editor/#B/fVLZbsIwEHznK1bqW6UYH0lI/qLqH0A5WpVi5FAph/zvnd04UFDaSEgJc3hmvc1n17x/nBfDvovN9N6SM9RRZlVBPWWuVpZCR6aIwV98YELmHMA5DiWSoWeCK0WSN5oxvWcm4rx3oi6XJBHD93FHKe+wGMDVzDTUkFYrGLE0bvy2u4FOA7XAzG9EOcYsY0CguqISmHWFuDKib65TzL8IEVlvD53X4dKMsRmmry25khCdh1ao0hYUWqrsGINMfP04HV4gGhlGY34GzSIld7GaSOyDMhwfLlmtwQve71ncSvOe2NriknLYv/mjD/RUaefMmi3byZFVcOtBiwh92h35o1Q1G+UyQVXBS6v/XESYQlmcbcBGi5r1uQyJf6P+ENYdbfCHHS1Sk5onu5LzVgA1ZmIfFdV06PLxmcpgZ3jUkA7XQaKIBBljGCoeikiInqppA0PPW92k0tiUuxTmmht03iU5gBcqsAffrpxVphLKzs1Nsjm+ZK3yOAZfxB8=) and that seems to work fine but not the basic boxes????

**Comment by after12am** [comment]
> [skyship](https://after12am.github.io/eisenscript-editor/#B/fVJbboMwEPznFCv1G8cPnreoegPSPBo1rSOTSoDlu3fWmNBGaZGQMLMzO7Ne35MUKnT9LvOHMfj1mLmv857w5bP+fezfTpfMD2QUjZRrUdJEuWmFJjeSKoOzV+u4IDcG4KMaSkUh22wo6sUOSdxnHiTJFEXsoiZFrBG2djeuoJFANTD1ExGGMc0YELBuaLTMvDKqMiJX1cXvXwXsdX3o0rlrP9tmmD52ZCqCdU5YikqX5AZq9GyDVHg5fR6fQZorlKQB7moKlNSj1FLEOgjD9qGStxJ1ztoDk4eYfCKW1phoAflXe7aOnhppjOpYclgUmQW1CWUBpj/3Zz5UomWhIk5QNNDCXf+jEonJlEZvhWqkaJlfxCHxO/OPrhtpix96lkhJWp5sHfvVACVmou8ZzdJ0c/8sYbA1PGpQ/W2QCBKNzDYUlXdBoomJmmUV3cQr2KfQ2JRfLtTNN8p5l2IDXijHGny7sVeVQgj9aG7Rm+FLlqIIlNb9Gw==)

Amazing😳 Super coooooooooool!!! 😳😳😳

**Comment by after12am** [comment]
@kronpano Thank you for the detailed explanation. How about this?

https://after12am.github.io/eisenscript-editor/#B/M1LQUqhWSKtUqFUwgjArgExDMLMCSFcqGAP5SfkVAA==

**Comment by kronpano** [comment]
Looking GOOD!!!!

I guess after the holidays I need to have a look at all the changes you have made.
Looks like you have pretty much implemented everything StructureSynth offers.

Need to get my head around all of it and see if I can get the BrowserSynth stuff somehow in.
Looking forward to playing with it!!

**Comment by after12am** [comment]
Sound good. Thanks for your support!

**Comment by after12am** [comment]
If something is wrong, please reopen.
